import test from 'node:test';
import assert from 'node:assert/strict';
import {missions,missionById} from '../src/content/missions.js';
import {freshState,execute,submitReport,nextCase,validateContent} from '../src/engine/game.js';
import {tokenize,normalizePath} from '../src/engine/parser.js';
import {parseSave,serializeSave} from '../src/storage/saves.js';
function run(s,...lines){return lines.reduce((s,line)=>execute(s,line).state,s);}
function collectAll(id,reverse=false){let s=run(freshState(id),'scope');const m=missionById(id);for(const n of (reverse?[...m.nodes].reverse():m.nodes)){if(!m.initialScope.includes(n.id))continue;s=run(s,'connect '+n.id);for(const f of n.files)s=run(s,'cat '+f.path,'collect '+f.id);}if(m.extension)s=run(s,'request-scope');if(m.puzzle)s=run(s,'solve '+m.puzzle.answers[0]);return s;}
test('all authored content references resolve',()=>assert.equal(validateContent(),true));
test('parser preserves quoted tokens and rejects incomplete quotes',()=>{assert.deepEqual(tokenize(' cat "/a b.txt" '),['cat','/a b.txt']);assert.throws(()=>tokenize('cat "oops'));assert.equal(normalizePath('../../logs/a','/docs'),'/logs/a');assert.throws(()=>tokenize('x'.repeat(2049)));});
test('unknown commands do not execute shell syntax',()=>{const s=freshState();const r=execute(s,'curl https://example.com');assert.match(r.output,/Unknown command/);assert.deepEqual(r.state.evidence,[]);assert.equal(s.tick,0);});
test('scope and out-of-scope boundaries',()=>{let s=freshState('halden');assert.match(execute(s,'connect maintenance').output,/scope first/);s=run(s,'scope');const r=execute(s,'connect office');assert.equal(r.state.node,null);assert.match(r.output,/outside/);assert.match(execute(s,'connect example.com').output,/Unknown simulated/);});
test('filesystem resolves relative paths and separates hosts',()=>{let s=run(freshState(),'scope','connect training','cd /docs','cat handover.txt');assert.ok(s.read.includes('handover'));assert.match(execute(s,'cat ../logs/missing').output,/not found/);});
test('evidence requires reading and collection is idempotent',()=>{let s=run(freshState(),'scope','connect training');assert.match(execute(s,'collect handover').output,/Read this/);s=run(s,'cat /docs/handover.txt','collect handover','collect handover');assert.deepEqual(s.evidence,['handover']);assert.equal(s.events.length,1);});
test('Halden response requires scope extension',()=>{let s=run(freshState('halden'),'scope','connect maintenance','cat /tasks/sync.task','collect task');assert.match(execute(s,'respond isolate-host').output,/scope/);s=run(s,'request-scope','respond isolate-host','verify');assert.equal(s.action,'isolate-host');assert.equal(s.verified,true);});
for(const m of missions){for(const reverse of [false,true])test(`${m.id}: ${reverse?'reverse':'normal'} evidence order completes with full score`,()=>{let s=collectAll(m.id,reverse);const a=m.actions[0];s=run(s,'connect '+a.node,'respond '+a.id,'verify');s=submitReport(s,m.correctFinding,m.requiredEvidence,true);assert.equal(s.report.score,100);assert.ok(s.completed.includes(m.id));assert.deepEqual(parseSave(serializeSave(s)),s);if(m.next)assert.equal(nextCase(s).missionId,m.next);});}
test('unsupported attribution and disruptive responses lose points',()=>{let s=collectAll('halden');s=run(s,'connect maintenance','respond shutdown-network','verify');s=submitReport(s,'vendor-guilty',['task','traffic','manifest','health'],false);assert.equal(s.report.parts.finding,0);assert.equal(s.report.parts.response,5);assert.equal(s.report.parts.verification,8);assert.ok(s.report.score<60);});
test('report needs action, verification, and cited preserved evidence',()=>{let s=collectAll('halden');assert.throws(()=>submitReport(s,'unauthorized-task',['task'],true));s=run(s,'connect maintenance','respond isolate-host','verify');assert.throws(()=>submitReport(s,'unauthorized-task',['fake'],true));const r=submitReport(s,'unauthorized-task',['task'],true);assert.equal(r.report.parts.finding,0);assert.throws(()=>submitReport(r,'unauthorized-task',['task'],true));});
test('invalid imports are rejected without changing existing state',()=>{const original=freshState();for(const patch of [{version:99},{contentVersion:99},{missionId:'unknown'},{node:'office'},{action:'fake'},{verified:true},{evidence:['handover']},{events:[{tick:-1,text:'bad'}]},{cwd:'/not-real'},{flags:['admin']}]){assert.throws(()=>parseSave(JSON.stringify({...original,...patch})));}assert.throws(()=>parseSave('{bad'));assert.throws(()=>parseSave('x'.repeat(1_000_001)));assert.deepEqual(original,freshState());});
test('save strips unexpected fields and rejects fabricated report score',()=>{const s=freshState();assert.equal(Object.hasOwn(parseSave(JSON.stringify({...s,arbitrary:'payload'})),'arbitrary'),false);let r=collectAll('cold-boot');r=run(r,'connect training','respond revoke-visitor','verify');r=submitReport(r,'expired-access',['handover','access'],true);r.report.score=999;assert.throws(()=>parseSave(JSON.stringify(r)));});
